### ISSUE TITLE
Error pages show up blank in IIS

### ISSUE THREAD

**Issue by natiox** [iaingalloway/ASP.NET-HttpErrors-Example#1]
The solution works when run locally in debug but when I deploy to an IIS 8.5 server, the error pages all come up blank.  W3 logs show 404s on /Home URLs.  Although this could be an IIS configuration issue?

**Comment by iaingalloway** [comment]
Hi, Natiox,

Sorry to hear you're having trouble. I know how much of a pain IIS configuration can be!
- Are you publishing this example, or your own code based on this example?
- What are the details of your IIS 8.5 server? Shared? Dedicated? Azure?

**Comment by natiox** [comment]
Publishing this unaltered example using a deployment package.  Dedicated IIS server on Windows Server 2012...accessing both from internal network and locally on the server.  I notice that going to /Error works in debug mode from Visual Studio but that gets a 404 on the server.  Wonder if it could be a routing issue?

**Comment by iaingalloway** [comment]
I'll see if I can replicate.

**Comment by iaingalloway** [comment]
Hi, Natiox,

I've tested deploying to a clean install of IIS 8.5 via FTP, Package, and WebDeploy and have been unable to replicate the behaviour you describe. The site behaves exactly as in the Azure Web Sites live example; in particular the three error pages give me the correct errors and status codes.

**Comment by natiox** [comment]
Thank you for all your efforts to replicate this.  If you ever need any info I can provide, or for me to try anything, just let me know.  I'll close the issue, since it could be a network or configuration issue of some kind.

**Comment by iokevins** [comment]
Hey natiox, I had this exact issue...GitHub solution works as-is in Visual Studio 2017 and IIS Express 10.x, but when deployed to IIS 7.5 in a site subfolder which I had converted to an app, I had to change path="/Error/Forbidden" to path="/MyAppFolder/Error/Forbidden"...otherwise I got empty/blank screen content with 403 forbidden or 404 not found errors, depending on environment (makes sense, in retrospect).

Hope this helps you,

Kevin
